---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smacon/public_html/eSpace
    - /bin/cp -rf backend/app/. $DEPLOYPATH/backend/app/
    - /bin/cp -rf backend/routes/. $DEPLOYPATH/backend/routes/
    - /bin/cp -rf backend/config/. $DEPLOYPATH/backend/config/
    - /bin/cp -rf backend/public/. $DEPLOYPATH/backend/public/
    - /bin/cp -f frontend/dist/index.html $DEPLOYPATH/index.html
    - /bin/cp -f frontend/dist/manifest.webmanifest $DEPLOYPATH/manifest.webmanifest
    - /bin/rm -f $DEPLOYPATH/registerSW.js
    - /bin/cp -f frontend/dist/sw.js $DEPLOYPATH/sw.js
    - /bin/cp -f frontend/dist/workbox-8553a241.js $DEPLOYPATH/workbox-8553a241.js
    - /bin/cp -rf frontend/dist/assets/. $DEPLOYPATH/assets/
