<?php

declare(strict_types=1);

namespace eSpace\App\Services;

use RuntimeException;

/**
 * Report Card Service
 *
 * Orchestrates report card generation: sources graded, student-visible assignment work
 * (assignment_submissions.status = 'returned' - existence of a returned submission is itself
 * proof of legitimate visibility, already gated by the marking workflow, so no separate
 * class/enrollment join is needed for sourcing), computes CBC-style weighted grades via
 * ReportCardGradingService, writes one Gemini call for all subjects' descriptors via
 * GeminiReportDescriptorService, and persists the result.
 *
 * Locking is a plain try/finally around GET_LOCK/RELEASE_LOCK entirely inside this service -
 * unlike Student\ENoteController::tutorExplain() (where the lock lived directly in the
 * controller, which calls Controller::success()/error() and those call exit(), so try/finally
 * couldn't be used there), this service never calls those response helpers itself, so a normal
 * try/finally is safe here and the controller never needs to know locking happened at all.
 */
class ReportCardService
{
    private function getDb()
    {
        return \eSpace\Config\Database::getInstance();
    }

    private function acquireLock(string $lockName, int $timeout = 30): bool
    {
        $stmt = $this->getDb()->prepare('SELECT GET_LOCK(:name, :timeout) AS acquired');
        $stmt->execute(['name' => $lockName, 'timeout' => $timeout]);
        $row = $stmt->fetch();
        return $row && (int) $row['acquired'] === 1;
    }

    private function releaseLock(string $lockName): void
    {
        $stmt = $this->getDb()->prepare('SELECT RELEASE_LOCK(:name)');
        $stmt->execute(['name' => $lockName]);
    }

    /**
     * Generate (or reuse cached) the full report card for a student's term - every subject they
     * have returned, graded work in, recomputed together with one batched Gemini call for all
     * subjects' descriptors. Restricted (by the controller) to the class teacher or admin.
     *
     * @throws RuntimeException On missing term/student, no graded work, or Gemini/lock failure.
     */
    public function generateFullReport(int $studentId, int $termId, int $actorId, string $actorRole, bool $force = false): array
    {
        return $this->withLock($studentId, $termId, fn() => $this->doGenerateReport($studentId, $termId, $actorId, $actorRole, $force, null));
    }

    /**
     * Generate (or reuse cached) just one subject's slice of a student's report card - used by a
     * subject teacher who isn't the class teacher, so no one has to wait for a single "owner" to
     * go first. Creates the parent report_cards shell if this is the first subject generated for
     * this student/term, and always recomputes the parent aggregates from every subject that
     * currently exists (not just this one) so a partial report's totals stay correct as more
     * subjects get added over time.
     *
     * @throws RuntimeException On missing term/student, no graded work in this subject, or Gemini/lock failure.
     */
    public function generateSubjectReport(int $studentId, int $termId, int $subjectId, int $actorId, string $actorRole, bool $force = false): array
    {
        return $this->withLock($studentId, $termId, fn() => $this->doGenerateReport($studentId, $termId, $actorId, $actorRole, $force, $subjectId));
    }

    private function withLock(int $studentId, int $termId, callable $work): array
    {
        $lockName = "report_card_{$studentId}_{$termId}";
        if (!$this->acquireLock($lockName, 30)) {
            throw new RuntimeException('This report is being generated by someone else right now. Please try again shortly.');
        }

        try {
            return $work();
        } finally {
            $this->releaseLock($lockName);
        }
    }

    private function doGenerateReport(int $studentId, int $termId, int $actorId, string $actorRole, bool $force, ?int $onlySubjectId): array
    {
        $db = $this->getDb();

        $term = $this->getTermRange($termId);
        if (!$term) {
            throw new RuntimeException('Term not found.');
        }

        $stmt = $db->prepare(
            'SELECT s.id, s.class_id, s.first_name, c.level AS class_level
             FROM students s
             LEFT JOIN classes c ON s.class_id = c.id
             WHERE s.id = :id AND s.deleted_at IS NULL'
        );
        $stmt->execute(['id' => $studentId]);
        $student = $stmt->fetch();
        if (!$student) {
            throw new RuntimeException('Student not found.');
        }

        $maxWeight = ReportCardGradingService::maxWeightForClassLevel($student['class_level']);

        $bySubject = $this->fetchGradedItemsBySubject($studentId, $term, $onlySubjectId);
        if (empty($bySubject)) {
            throw new RuntimeException($onlySubjectId
                ? 'This student has no returned, graded assignments for this subject/term yet.'
                : 'This student has no returned, graded assignments for this term yet.');
        }

        $totalsBySubject = $this->fetchTotalAssignmentCounts($studentId, $term);
        $subjectNames = $this->fetchSubjectNames(array_keys($bySubject));

        $computed = [];
        $sourceHashes = [];
        foreach ($bySubject as $subjectId => $items) {
            $weights = [];
            $constructs = [];
            $hashParts = [];
            $lastTeacherId = null;

            foreach ($items as $item) {
                $pct = (float) $item['percentage'];
                $weight = ReportCardGradingService::percentageToWeight($pct, $maxWeight);
                $weights[] = $weight;
                $constructs[] = [
                    'assignment_id' => (int) $item['assignment_id'],
                    'construct_label' => $item['title'],
                    'score_obtained' => (float) $item['total_score'],
                    'score_total' => (float) $item['total_marks'],
                    'weight' => $weight,
                ];
                $hashParts[] = $item['assignment_id'] . ':' . round($pct, 2);
                $lastTeacherId = (int) $item['teacher_id'];
            }

            $avgWeight = ReportCardGradingService::averageWeight($weights);
            $grade = ReportCardGradingService::weightToGrade($avgWeight, $maxWeight);

            $computed[$subjectId] = [
                'subject_id' => $subjectId,
                'subject_name' => $subjectNames[$subjectId] ?? 'Subject',
                'avg_weight' => $avgWeight,
                'grade' => $grade,
                'performance_level' => ReportCardGradingService::weightToPerformanceLevel($avgWeight, $maxWeight),
                'constructs' => $constructs,
                'competencies' => $student['class_id']
                    ? $this->buildCompetencies($studentId, $subjectId, $termId, (int) $student['class_id'], $student['class_level'], $student['first_name'], $subjectNames[$subjectId] ?? 'Subject')
                    : [],
                'teacher_id' => $lastTeacherId,
                'assignments_included_count' => count($items),
                'assignments_total_count' => $totalsBySubject[$subjectId] ?? count($items),
            ];
            $sourceHashes[$subjectId] = hash('sha256', implode('|', $hashParts));
        }

        if (!$force) {
            $existing = $this->getExistingReportWithHashes($studentId, $termId);
            if ($existing) {
                $relevantHashes = $onlySubjectId ? [$onlySubjectId => $sourceHashes[$onlySubjectId]] : $sourceHashes;
                if ($this->hashesMatch($existing['subject_hashes'], $relevantHashes, !$onlySubjectId)) {
                    return $this->getFullReport($existing['report_card_id']);
                }
            }
        }

        $subjectIds = array_keys($computed);
        $descriptorInput = [];
        foreach ($subjectIds as $subjectId) {
            $s = $computed[$subjectId];
            $items = [];
            foreach ($bySubject[$subjectId] as $item) {
                $items[] = ['title' => $item['title'], 'percentage' => (float) $item['percentage']];
            }
            $descriptorInput[] = [
                'subject_name' => $s['subject_name'],
                'grade' => $s['grade'],
                'performance_level' => $s['performance_level'],
                'avg_weight' => $s['avg_weight'],
                'items' => $items,
            ];
        }

        $descriptors = array_fill(0, count($subjectIds), null);
        try {
            $descriptors = (new GeminiReportDescriptorService())->generateDescriptors($descriptorInput);
        } catch (RuntimeException $e) {
            // Deliberately swallowed: grades/weights are already computed and worth keeping even
            // if descriptor text couldn't be generated this time - see class docblock.
        }

        $reportCardId = $this->ensureReportShell($studentId, $termId, $student['class_id'] !== null ? (int) $student['class_id'] : null);

        foreach ($subjectIds as $i => $subjectId) {
            $subjectRowId = $this->upsertReportCardSubject($reportCardId, $computed[$subjectId], $sourceHashes[$subjectId], $descriptors[$i] ?? null);
            $this->upsertReportCardCompetencies($subjectRowId, $computed[$subjectId]['competencies']);
        }

        $this->recomputeReportAggregates($reportCardId, $actorId, $actorRole);

        if ($onlySubjectId === null) {
            $this->generateSummaryComments($reportCardId, $computed);

            (new NotificationService())->notify(
                $studentId,
                'student',
                'report_card_ready',
                'Report card ready',
                "Your report card for {$term['name']} has been generated and is ready to view.",
                ['report_card_id' => $reportCardId, 'term_id' => $termId]
            );
        }

        return $this->getFullReport($reportCardId);
    }

    /**
     * Auto-writes the Class Teacher's and Head Teacher's comments from the student's computed
     * overall performance for the term - only run for full-report generation (a single subject's
     * regeneration doesn't represent the whole term's standing). Left untouched on failure, same
     * "don't lose what already worked" approach as the per-subject descriptors.
     *
     * @param array<int, array{subject_name: string, grade: string, performance_level: string}> $computedSubjects
     */
    private function generateSummaryComments(int $reportCardId, array $computedSubjects): void
    {
        $db = $this->getDb();
        $stmt = $db->prepare(
            'SELECT rc.total_points, rc.overall_avg_weight, rc.performance_level, s.first_name
             FROM report_cards rc INNER JOIN students s ON rc.student_id = s.id WHERE rc.id = :id'
        );
        $stmt->execute(['id' => $reportCardId]);
        $row = $stmt->fetch();
        if (!$row) {
            return;
        }

        $subjects = array_map(fn($s) => [
            'subject_name' => $s['subject_name'],
            'grade' => $s['grade'],
            'performance_level' => $s['performance_level'],
        ], array_values($computedSubjects));

        try {
            $comments = (new GeminiReportDescriptorService())->generateSummaryComments([
                'student_first_name' => $row['first_name'],
                'total_points' => (int) $row['total_points'],
                'overall_avg_weight' => (float) $row['overall_avg_weight'],
                'performance_level' => $row['performance_level'],
                'subjects' => $subjects,
            ]);
        } catch (RuntimeException $e) {
            return;
        }

        $stmt = $db->prepare(
            'UPDATE report_cards SET class_teacher_comment = :ctc, head_teacher_comment = :htc, updated_at = NOW() WHERE id = :id'
        );
        $stmt->execute([
            'ctc' => $comments['class_teacher_comment'],
            'htc' => $comments['head_teacher_comment'],
            'id' => $reportCardId,
        ]);
    }

    /**
     * Create the parent report_cards row if it doesn't exist yet (aggregates start at zero and
     * are filled in by recomputeReportAggregates() right after subjects are written) - lets a
     * subject teacher generate before anyone else has touched this student's report.
     */
    private function ensureReportShell(int $studentId, int $termId, ?int $classId): int
    {
        $db = $this->getDb();

        $stmt = $db->prepare('SELECT id FROM report_cards WHERE student_id = :student_id AND term_id = :term_id');
        $stmt->execute(['student_id' => $studentId, 'term_id' => $termId]);
        $existing = $stmt->fetch();
        if ($existing) {
            return (int) $existing['id'];
        }

        $stmt = $db->prepare(
            "INSERT INTO report_cards (student_id, term_id, class_id, total_points, overall_avg_weight, generated_at, created_at, updated_at)
             VALUES (:student_id, :term_id, :class_id, 0, 0.0, NOW(), NOW(), NOW())"
        );
        $stmt->execute(['student_id' => $studentId, 'term_id' => $termId, 'class_id' => $classId]);

        return (int) $db->lastInsertId();
    }

    /**
     * Recompute report_cards' aggregates (total_points, overall_avg_weight, performance_level,
     * result_category) from every report_card_subjects row that currently exists for this
     * report - not just the subject(s) just written - so a partial report's totals stay correct
     * as more subject teachers generate their slice over time.
     */
    private function recomputeReportAggregates(int $reportCardId, int $actorId, string $actorRole): void
    {
        $db = $this->getDb();

        $stmt = $db->prepare(
            'SELECT c.level AS class_level FROM report_cards rc LEFT JOIN classes c ON rc.class_id = c.id WHERE rc.id = :id'
        );
        $stmt->execute(['id' => $reportCardId]);
        $classLevel = $stmt->fetch()['class_level'] ?? null;
        $maxWeight = ReportCardGradingService::maxWeightForClassLevel($classLevel);

        $stmt = $db->prepare('SELECT avg_weight, grade FROM report_card_subjects WHERE report_card_id = :id');
        $stmt->execute(['id' => $reportCardId]);
        $rows = $stmt->fetchAll();

        if (empty($rows)) {
            return;
        }

        $avgWeights = array_map(fn($r) => (float) $r['avg_weight'], $rows);
        $overallAvgWeight = round(array_sum($avgWeights) / count($avgWeights), 1);
        $performanceLevel = ReportCardGradingService::weightToPerformanceLevel($overallAvgWeight, $maxWeight);
        $totalPoints = array_sum(array_map(fn($r) => ReportCardGradingService::gradeToPrinciplePoints($r['grade'], $maxWeight), $rows));
        $resultCategory = ReportCardGradingService::resultCategory($overallAvgWeight, $maxWeight);

        $stmt = $db->prepare(
            "UPDATE report_cards SET total_points = :total_points, overall_avg_weight = :overall_avg_weight,
                 performance_level = :performance_level, result_category = :result_category,
                 generated_at = NOW(), generated_by = :generated_by, generated_by_role = :generated_by_role, updated_at = NOW()
             WHERE id = :id"
        );
        $stmt->execute([
            'total_points' => $totalPoints,
            'overall_avg_weight' => $overallAvgWeight,
            'performance_level' => $performanceLevel,
            'result_category' => $resultCategory,
            'generated_by' => $actorId,
            'generated_by_role' => $actorRole,
            'id' => $reportCardId,
        ]);
    }

    private function getTermRange(int $termId): ?array
    {
        $stmt = $this->getDb()->prepare('SELECT id, name, start_date, end_date, academic_year_id FROM terms WHERE id = :id AND deleted_at IS NULL');
        $stmt->execute(['id' => $termId]);
        return $stmt->fetch() ?: null;
    }

    /**
     * Every returned (student-visible) submission within the term's date window, grouped by
     * subject - assignments have no term_id FK, only due_date, so that's the filter used. Pass
     * $onlySubjectId to scope to a single subject (the per-subject generation tier).
     */
    private function fetchGradedItemsBySubject(int $studentId, array $term, ?int $onlySubjectId = null): array
    {
        $subjectFilter = $onlySubjectId ? ' AND a.subject_id = :subject_id' : '';

        $stmt = $this->getDb()->prepare(
            "SELECT a.id AS assignment_id, a.title, a.subject_id, a.teacher_id, a.total_marks,
                    s.total_score, s.percentage
             FROM assignment_submissions s
             INNER JOIN assignments a ON s.assignment_id = a.id
             WHERE s.student_id = :student_id AND s.status IN ('graded', 'returned')
               AND a.status = 'published' AND a.subject_id IS NOT NULL AND a.deleted_at IS NULL
               AND a.due_date BETWEEN :start_date AND :end_date{$subjectFilter}
             ORDER BY a.subject_id, a.due_date ASC"
        );
        $params = [
            'student_id' => $studentId,
            'start_date' => $term['start_date'],
            'end_date' => $term['end_date'],
        ];
        if ($onlySubjectId) {
            $params['subject_id'] = $onlySubjectId;
        }
        $stmt->execute($params);

        $bySubject = [];
        foreach ($stmt->fetchAll() as $row) {
            $bySubject[(int) $row['subject_id']][] = $row;
        }

        return $bySubject;
    }

    private function fetchTotalAssignmentCounts(int $studentId, array $term): array
    {
        $stmt = $this->getDb()->prepare(
            "SELECT a.subject_id, COUNT(DISTINCT s.assignment_id) as total
             FROM assignment_submissions s
             INNER JOIN assignments a ON s.assignment_id = a.id
             WHERE s.student_id = :student_id AND a.subject_id IS NOT NULL AND a.deleted_at IS NULL
               AND a.due_date BETWEEN :start_date AND :end_date
             GROUP BY a.subject_id"
        );
        $stmt->execute(['student_id' => $studentId, 'start_date' => $term['start_date'], 'end_date' => $term['end_date']]);

        $totals = [];
        foreach ($stmt->fetchAll() as $row) {
            $totals[(int) $row['subject_id']] = (int) $row['total'];
        }

        return $totals;
    }

    private function fetchSubjectNames(array $subjectIds): array
    {
        if (empty($subjectIds)) {
            return [];
        }

        $placeholders = implode(',', array_fill(0, count($subjectIds), '?'));
        $stmt = $this->getDb()->prepare("SELECT id, name FROM subjects WHERE id IN ({$placeholders})");
        $stmt->execute($subjectIds);

        $names = [];
        foreach ($stmt->fetchAll() as $row) {
            $names[(int) $row['id']] = $row['name'];
        }

        return $names;
    }

    private function getTeacherInitials(?int $teacherId): ?string
    {
        if (!$teacherId) {
            return null;
        }

        $stmt = $this->getDb()->prepare('SELECT first_name, last_name FROM teachers WHERE id = :id');
        $stmt->execute(['id' => $teacherId]);
        $teacher = $stmt->fetch();

        if (!$teacher || empty($teacher['first_name'])) {
            return null;
        }

        return strtoupper(substr($teacher['first_name'], 0, 1) . '.' . substr($teacher['last_name'] ?? '', 0, 1));
    }

    private function getExistingReportWithHashes(int $studentId, int $termId): ?array
    {
        $stmt = $this->getDb()->prepare('SELECT id FROM report_cards WHERE student_id = :student_id AND term_id = :term_id');
        $stmt->execute(['student_id' => $studentId, 'term_id' => $termId]);
        $report = $stmt->fetch();

        if (!$report) {
            return null;
        }

        $stmt = $this->getDb()->prepare('SELECT subject_id, source_hash FROM report_card_subjects WHERE report_card_id = :id');
        $stmt->execute(['id' => $report['id']]);

        $hashes = [];
        foreach ($stmt->fetchAll() as $row) {
            $hashes[(int) $row['subject_id']] = $row['source_hash'];
        }

        return ['report_card_id' => (int) $report['id'], 'subject_hashes' => $hashes];
    }

    /**
     * @param bool $requireSameCount True for full-report comparisons (every subject must be
     *     present and unchanged); false for a single-subject comparison, where $freshHashes has
     *     just the one subject being checked and other existing subjects are irrelevant.
     */
    private function hashesMatch(array $existingHashes, array $freshHashes, bool $requireSameCount = true): bool
    {
        if ($requireSameCount && count($existingHashes) !== count($freshHashes)) {
            return false;
        }

        foreach ($freshHashes as $subjectId => $hash) {
            if (!isset($existingHashes[$subjectId]) || $existingHashes[$subjectId] !== $hash) {
                return false;
            }
        }

        return true;
    }

    /**
     * LOA/AOI/EOC competency breakdown for one subject - only populated for categories that have
     * at least one eligible, tagged assessment; a subject with none returns an empty array so the
     * frontend's hybrid fallback (legacy constructs table only) kicks in naturally.
     *
     * @return array<int, array{category: string, percentage: float, status: string, performance_descriptor: string, weight: int, descriptor_text: string, source_count: int}>
     */
    private function buildCompetencies(int $studentId, int $subjectId, int $termId, int $classId, ?string $classLevel, string $studentFirstName, string $subjectName): array
    {
        $service = new CompetencyReportService();
        $competencies = [];

        foreach (['LOA', 'AOI', 'EOC'] as $category) {
            $average = $service->calculateAssessmentAverage($studentId, $subjectId, $termId, $classId, $category);
            if ($average['count'] === 0 || $average['percentage'] === null) {
                continue;
            }

            $percentage = $average['percentage'];
            $level = ReportCardGradingService::getPerformanceLevel($percentage);
            $weight = ReportCardGradingService::convertToWeight($percentage, $classLevel);

            if ($category === 'LOA') {
                $learningOutcomes = $service->getLearningOutcomesForAssignments($average['assignment_ids']);
                $descriptor = $service->generateLOADescriptor($studentFirstName, $learningOutcomes, $percentage);
            } elseif ($category === 'AOI') {
                $competenceTexts = $service->getCompetenciesForAssignments($average['assignment_ids']);
                $descriptor = $service->generateAOIDescriptor($studentFirstName, $competenceTexts[0] ?? '', $percentage);
            } else {
                $topicBreakdown = $service->calculateTopicBreakdown($studentId, $subjectId, $termId, $classId);
                $descriptor = $service->generateEOCDescriptor($studentFirstName, $subjectName, $topicBreakdown);
            }

            $competencies[] = [
                'category' => $category,
                'percentage' => $percentage,
                'status' => $level['status'],
                'performance_descriptor' => $level['descriptor'],
                'weight' => $weight,
                'descriptor_text' => $descriptor,
                'source_count' => $average['count'],
            ];
        }

        return $competencies;
    }

    private function upsertReportCardCompetencies(int $reportCardSubjectId, array $competencies): void
    {
        $db = $this->getDb();

        // Replace wholesale, same approach as constructs - simplest correct behavior for a
        // regenerate (a category that no longer has eligible marks should disappear, not linger).
        $stmt = $db->prepare('DELETE FROM report_card_competencies WHERE report_card_subject_id = :id');
        $stmt->execute(['id' => $reportCardSubjectId]);

        if (empty($competencies)) {
            return;
        }

        $insert = $db->prepare(
            "INSERT INTO report_card_competencies
                (report_card_subject_id, assessment_category, percentage, status, performance_descriptor, weight, descriptor_text, source_count, created_at, updated_at)
             VALUES (:report_card_subject_id, :category, :percentage, :status, :descriptor, :weight, :descriptor_text, :source_count, NOW(), NOW())"
        );
        foreach ($competencies as $c) {
            $insert->execute([
                'report_card_subject_id' => $reportCardSubjectId,
                'category' => $c['category'],
                'percentage' => $c['percentage'],
                'status' => $c['status'],
                'descriptor' => $c['performance_descriptor'],
                'weight' => $c['weight'],
                'descriptor_text' => $c['descriptor_text'],
                'source_count' => $c['source_count'],
            ]);
        }
    }

    private function upsertReportCardSubject(int $reportCardId, array $subject, string $sourceHash, ?string $descriptorText): int
    {
        $db = $this->getDb();
        $teacherInitials = $this->getTeacherInitials($subject['teacher_id']);

        $stmt = $db->prepare(
            "INSERT INTO report_card_subjects
                (report_card_id, subject_id, avg_weight, grade, descriptor_text, teacher_initials, assignments_included_count, assignments_total_count, source_hash, created_at, updated_at)
             VALUES (:report_card_id, :subject_id, :avg_weight, :grade, :descriptor_text, :teacher_initials, :included, :total, :source_hash, NOW(), NOW())
             ON DUPLICATE KEY UPDATE avg_weight = :avg_weight2, grade = :grade2,
                 descriptor_text = COALESCE(:descriptor_text2, descriptor_text), teacher_initials = :teacher_initials2,
                 assignments_included_count = :included2, assignments_total_count = :total2, source_hash = :source_hash2, updated_at = NOW()"
        );
        $stmt->execute([
            'report_card_id' => $reportCardId,
            'subject_id' => $subject['subject_id'],
            'avg_weight' => $subject['avg_weight'],
            'grade' => $subject['grade'],
            'descriptor_text' => $descriptorText,
            'teacher_initials' => $teacherInitials,
            'included' => $subject['assignments_included_count'],
            'total' => $subject['assignments_total_count'],
            'source_hash' => $sourceHash,
            'avg_weight2' => $subject['avg_weight'],
            'grade2' => $subject['grade'],
            'descriptor_text2' => $descriptorText,
            'teacher_initials2' => $teacherInitials,
            'included2' => $subject['assignments_included_count'],
            'total2' => $subject['assignments_total_count'],
            'source_hash2' => $sourceHash,
        ]);

        $stmt = $db->prepare('SELECT id FROM report_card_subjects WHERE report_card_id = :report_card_id AND subject_id = :subject_id');
        $stmt->execute(['report_card_id' => $reportCardId, 'subject_id' => $subject['subject_id']]);
        $subjectRowId = (int) $stmt->fetch()['id'];

        // Replace constructs wholesale - simplest correct approach for a full regenerate.
        $stmt = $db->prepare('DELETE FROM report_card_constructs WHERE report_card_subject_id = :id');
        $stmt->execute(['id' => $subjectRowId]);

        $insertConstruct = $db->prepare(
            "INSERT INTO report_card_constructs (report_card_subject_id, assignment_id, construct_label, score_obtained, score_total, weight, created_at)
             VALUES (:report_card_subject_id, :assignment_id, :construct_label, :score_obtained, :score_total, :weight, NOW())"
        );
        foreach ($subject['constructs'] as $construct) {
            $insertConstruct->execute([
                'report_card_subject_id' => $subjectRowId,
                'assignment_id' => $construct['assignment_id'],
                'construct_label' => $construct['construct_label'],
                'score_obtained' => $construct['score_obtained'],
                'score_total' => $construct['score_total'],
                'weight' => $construct['weight'],
            ]);
        }

        return $subjectRowId;
    }

    /**
     * Assemble the full nested response shape for a report card - reused by the generate flow's
     * return value and by plain "view" endpoints that don't regenerate anything.
     */
    public function getFullReport(int $reportCardId): array
    {
        $db = $this->getDb();

        $stmt = $db->prepare(
            "SELECT rc.*, s.first_name, s.last_name, s.admission_number, c.name AS class_name, c.stream_name, c.level AS class_level,
                    t.name AS term_name, t.start_date AS term_start_date, t.end_date AS term_end_date, ay.name AS academic_year_name
             FROM report_cards rc
             INNER JOIN students s ON rc.student_id = s.id
             LEFT JOIN classes c ON rc.class_id = c.id
             INNER JOIN terms t ON rc.term_id = t.id
             LEFT JOIN academic_years ay ON t.academic_year_id = ay.id
             WHERE rc.id = :id"
        );
        $stmt->execute(['id' => $reportCardId]);
        $report = $stmt->fetch();

        if (!$report) {
            throw new RuntimeException('Report card not found.');
        }

        $stmt = $db->prepare(
            "SELECT rcs.*, sub.name AS subject_name, sub.code AS subject_code
             FROM report_card_subjects rcs
             INNER JOIN subjects sub ON rcs.subject_id = sub.id
             WHERE rcs.report_card_id = :report_card_id
             ORDER BY sub.name ASC"
        );
        $stmt->execute(['report_card_id' => $reportCardId]);
        $subjectRows = $stmt->fetchAll();

        $subjects = [];
        foreach ($subjectRows as $row) {
            $stmt2 = $db->prepare('SELECT * FROM report_card_constructs WHERE report_card_subject_id = :id ORDER BY id ASC');
            $stmt2->execute(['id' => $row['id']]);

            $stmt3 = $db->prepare(
                "SELECT * FROM report_card_competencies WHERE report_card_subject_id = :id
                 ORDER BY FIELD(assessment_category, 'LOA', 'AOI', 'EOC')"
            );
            $stmt3->execute(['id' => $row['id']]);

            $subjects[] = [
                'subject_id' => (int) $row['subject_id'],
                'subject_name' => $row['subject_name'],
                'subject_code' => $row['subject_code'],
                'avg_weight' => (float) $row['avg_weight'],
                'grade' => $row['grade'],
                'descriptor_text' => $row['descriptor_text'],
                'teacher_initials' => $row['teacher_initials'],
                'assignments_included_count' => (int) $row['assignments_included_count'],
                'assignments_total_count' => (int) $row['assignments_total_count'],
                'constructs' => array_map(fn($c) => [
                    'label' => $c['construct_label'],
                    'score_obtained' => (float) $c['score_obtained'],
                    'score_total' => (float) $c['score_total'],
                    'weight' => (int) $c['weight'],
                ], $stmt2->fetchAll()),
                'competencies' => array_map(fn($c) => [
                    'category' => $c['assessment_category'],
                    'percentage' => (float) $c['percentage'],
                    'status' => $c['status'],
                    'performance_descriptor' => $c['performance_descriptor'],
                    'weight' => (int) $c['weight'],
                    'descriptor_text' => $c['descriptor_text'],
                    'source_count' => (int) $c['source_count'],
                ], $stmt3->fetchAll()),
            ];
        }

        $stmt = $db->prepare(
            'SELECT COUNT(*) AS login_count FROM student_logins
             WHERE student_id = :student_id AND logged_in_at >= :start_date AND logged_in_at < DATE_ADD(:end_date, INTERVAL 1 DAY)'
        );
        $stmt->execute([
            'student_id' => $report['student_id'],
            'start_date' => $report['term_start_date'],
            'end_date' => $report['term_end_date'],
        ]);
        $loginCount = (int) $stmt->fetch()['login_count'];

        $stmt = $db->query('SELECT * FROM school_settings WHERE id = 1');
        $school = $stmt->fetch() ?: null;

        $maxAwards = $school ? max(1, (int) $school['max_awards_on_report_card']) : 2;
        $awards = $this->topAwardsForReport(
            (new RewardService())->listAwardsForStudent((int) $report['student_id'], true, (int) $report['term_id']),
            $maxAwards
        );

        $virtualLab = (new VirtualLabService())->listResultsForStudent((int) $report['student_id'], (int) $report['term_id']);

        return [
            'id' => (int) $report['id'],
            'student' => [
                'id' => (int) $report['student_id'],
                'first_name' => $report['first_name'],
                'last_name' => $report['last_name'],
                'admission_number' => $report['admission_number'],
            ],
            'term' => [
                'id' => (int) $report['term_id'],
                'name' => $report['term_name'],
                'academic_year' => $report['academic_year_name'],
            ],
            'class_name' => $report['class_name'],
            'stream_name' => $report['stream_name'],
            'class_level' => $report['class_level'],
            'max_weight' => ReportCardGradingService::maxWeightForClassLevel($report['class_level']),
            'total_points' => (int) $report['total_points'],
            'overall_avg_weight' => (float) $report['overall_avg_weight'],
            'performance_level' => $report['performance_level'],
            'result_category' => (int) $report['result_category'],
            'class_teacher_comment' => $report['class_teacher_comment'],
            'head_teacher_comment' => $report['head_teacher_comment'],
            'generated_at' => $report['generated_at'],
            'login_count' => $loginCount,
            'school' => $school,
            'subjects' => $subjects,
            'awards' => $awards,
            'virtual_lab' => $virtualLab,
        ];
    }

    /**
     * A student can accumulate more active badges than a one-page report card has room for.
     * Show only the school's configured cap, keeping the most prestigious ones - platinum first,
     * down through the percentage tiers, with the class/subject "special" recognitions last since
     * every percentage-tier badge already implies a broader achievement than a single-category one.
     * Ties broken by the higher score/average, then the most recently awarded.
     */
    private function topAwardsForReport(array $awards, int $maxAwards): array
    {
        $tierRank = ['platinum' => 1, 'gold' => 2, 'silver' => 3, 'bronze' => 4, 'special' => 5];

        usort($awards, function ($a, $b) use ($tierRank) {
            $rankA = $tierRank[$a['badge_type']] ?? 6;
            $rankB = $tierRank[$b['badge_type']] ?? 6;
            if ($rankA !== $rankB) {
                return $rankA <=> $rankB;
            }
            $scoreA = $a['average'] ?? $a['score'] ?? -1;
            $scoreB = $b['average'] ?? $b['score'] ?? -1;
            if ($scoreA !== $scoreB) {
                return $scoreB <=> $scoreA;
            }
            return strcmp($b['awarded_at'], $a['awarded_at']);
        });

        return array_slice($awards, 0, $maxAwards);
    }
}
