-- AI Tutor: teacher-style spoken explanations of eNote pages, generated by an LLM and then
-- converted to speech via the existing ElevenLabs pipeline. Kept in a separate table from
-- enote_page_narrations (word-for-word Read Aloud) since the two are independent features with
-- independent content (raw notes vs. AI-generated explanation) - regenerating one never touches
-- the other.
CREATE TABLE IF NOT EXISTS `enote_page_tutor_explanations` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `page_id` INT UNSIGNED NOT NULL,
    `voice` VARCHAR(20) NOT NULL,
    `explanation_text` LONGTEXT NOT NULL,
    `audio_path` VARCHAR(255) NOT NULL,
    `content_hash` CHAR(64) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_page_voice_tutor` (`page_id`, `voice`),
    KEY `idx_tutor_explanations_page_id` (`page_id`),
    CONSTRAINT `fk_tutor_explanations_page` FOREIGN KEY (`page_id`) REFERENCES `enote_pages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
