-- New admin-curated template: "Determining Relative Density of Metal Samples by Spring Extension"
-- (O-Level Physics Practical Workbook, Item 10 - six 100g metal "gold-lookalike" samples M1-M6,
-- tested to see which (if any) are consistent with pure silver). A bespoke 3D scene
-- (VirtualLabSceneSilverDensity.vue, render_component 'silver_density_spring') reuses the existing
-- retort_stand/spring/ruler/beaker/mass_piece models - the same tall, shoulder-height retort stand
-- and spring-and-pointer rig as Hooke's Law, Pendulum and Titration (same proportions, no apparatus
-- of its own). A thread carries the hanging metal the rest of the way down to a beaker standing
-- directly on the bench - the same role the real apparatus's 20cm thread plays - so no riser block
-- is needed; immersing a sample lowers it further down that same thread, into the water.
--
-- Physics: the student first measures a reference (unloaded) pointer position once, reused for
-- every sample. Each 100g sample then gives roughly the same air reading (so e_a = air - reference
-- is roughly constant across all six - itself worth noticing), but a different upthrust once
-- immersed depending on the sample's own density, so the water reading (and e_w) varies. Relative
-- density by the loss-of-weight method: R.D. = e_a / (e_a - e_w), density = 1000 x R.D. (kg/m3) -
-- compared against pure silver's 10200-10500 kg/m3 range. Each metal's true density is a hidden
-- constant in the Vue component (TRUE_DENSITY_KGM3), the same "hidden value graded against" approach
-- as the concave mirror's true focal length; three of the six are genuine silver, three are not, so
-- the class discussion has a real answer either way.
--
-- Each trial (a raw air reading then a raw water reading for one metal, both against the one shared
-- reference reading) is paired client-side in VirtualLabExperiment.vue
-- (lastDensityAirCm/lastDensityWaterCm/lastDensityReferenceCm/lastDensityMetalKey) into one Results
-- Table row, same pattern as the concave mirror's u/v pairing. The graph plots density against metal
-- number - with only six discrete samples rather than a continuously varying quantity, a line of
-- best fit through the origin doesn't apply here the way it does for the other physics graphs, but a
-- scatter of each sample's density immediately shows which ones fall inside the silver band.

INSERT INTO `virtual_lab_experiments`
    (`title`, `subject_id`, `topic`, `category`, `difficulty`, `created_by`, `objective`, `introduction`, `apparatus`, `materials`, `safety_precautions`, `scene_objects`, `conclusion_prompt`, `marks`, `is_template`, `status`, `render_mode`, `render_component`)
VALUES (
    'Determining Relative Density of Metal Samples by Spring Extension', (SELECT id FROM subjects WHERE name = 'PHY' LIMIT 1), 'Density and Relative Density', 'physics', 'intermediate', NULL,
    'To determine the relative density (and hence the density) of six metal samples by the loss-of-weight method, and use it to decide which are consistent with pure silver.',
    'A group of students on a trip picked up some rare-looking metals that looked like gold, and argued about whether they were worth a fortune or not. One of them suggested testing them in the school laboratory instead of guessing. As one of the students, you will hang each 100g sample (labelled M1 to M6) from a spring on a thread, and read the pointer''s position against a rule - first with nothing attached (the reference reading), then with the sample hanging in air, then with it fully immersed in water. Because the upthrust in water depends on the sample''s volume - and so on its density - the readings let you calculate each sample''s relative density (R.D. = e_a / (e_a - e_w)) and its density in kg/m3, without ever weighing it on a balance. Pure silver has a density of 10200 to 10500 kg/m3 - use your results to advise your friends which samples, if any, are consistent with being silver.',
    '1 retort stand with clamp, 1 spring with a pointer, 1 metre rule, a thread, 1 beaker of water, 6 metal samples (M1-M6) each of mass 100g.',
    'None (all apparatus is simulated).',
    'Lower each sample gently until it is fully immersed without touching the sides or bottom of the beaker; let the pointer become stationary before reading it; read the pointer with your eye level with the scale, to avoid parallax error; handle the beaker of water carefully.',
    '[{"key":"stand1","object_type":"retort_stand","position":{"x":-1.2,"y":0,"z":0},"in_tray":true},{"key":"spring1","object_type":"spring","position":{"x":-1.2,"y":0,"z":0.6},"props":{"natural_length_cm":10,"spring_constant_n_per_m":5},"in_tray":true},{"key":"rule1","object_type":"ruler","position":{"x":1.2,"y":0,"z":0},"in_tray":true},{"key":"beaker1","object_type":"beaker","position":{"x":0.8,"y":0,"z":0.6},"props":{"color":"#bcd9f2"},"in_tray":true},{"key":"metal1","object_type":"mass_piece","position":{"x":0.2,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true},{"key":"metal2","object_type":"mass_piece","position":{"x":0.45,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true},{"key":"metal3","object_type":"mass_piece","position":{"x":0.7,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true},{"key":"metal4","object_type":"mass_piece","position":{"x":0.95,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true},{"key":"metal5","object_type":"mass_piece","position":{"x":1.2,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true},{"key":"metal6","object_type":"mass_piece","position":{"x":1.45,"y":0,"z":1.0},"props":{"mass_g":100},"in_tray":true}]',
    'Based on your results, which of the six metal samples (M1-M6) are consistent with pure silver? Explain how the spring-extension method let you tell them apart even though they are all the same mass and look identical.',
    20.00, 1, 'published', '2d', 'silver_density_spring'
);

SET @density_id = (SELECT id FROM `virtual_lab_experiments` WHERE `title` = 'Determining Relative Density of Metal Samples by Spring Extension' AND `is_template` = 1 ORDER BY id DESC LIMIT 1);

INSERT INTO `virtual_lab_steps` (`experiment_id`, `step_number`, `instruction`, `target_object_key`, `required_action`, `expected_value`, `tolerance`, `hint`, `feedback_correct`, `feedback_incorrect`, `is_safety_check`) VALUES
(@density_id, 1, 'Pick up any piece of apparatus from the tray to start setting up the bench.', NULL, 'move', 'tray', NULL, 'Click an item in the apparatus tray.', 'Item placed on the bench.', 'Click an item in the apparatus tray.', 0),
(@density_id, 2, 'Pick up another piece of apparatus.', NULL, 'move', 'tray', NULL, 'Click another item in the apparatus tray.', 'Item placed on the bench.', 'Click an item in the apparatus tray.', 0),
(@density_id, 3, 'Pick up another piece of apparatus.', NULL, 'move', 'tray', NULL, 'Click another item in the apparatus tray.', 'Item placed on the bench.', 'Click an item in the apparatus tray.', 0),
(@density_id, 4, 'Pick up the last of the retort stand, spring, rule and beaker.', NULL, 'move', 'tray', NULL, 'Click the remaining item in the apparatus tray.', 'Core apparatus is now on the bench.', 'Click the remaining item in the apparatus tray.', 0),
(@density_id, 5, 'Hang the spring on the retort stand''s clamp.', 'spring1', 'move', 'stand1', NULL, 'Drag the spring so it sits close to the stand''s clamp.', 'Spring mounted - its pointer now hangs against the rule.', 'Select the spring and drag it onto the stand.', 0),
(@density_id, 6, 'With nothing on the hook yet, select the rule, click Measure, then click the spring to record the reference (unloaded) pointer position. You will reuse this one reading for every sample.', NULL, 'measure', NULL, NULL, 'This reading is the zero point - every later extension is measured from it.', 'Reference position recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 7, 'Pick up M1 from the tray and hang it on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M1 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 8, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M1''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M1 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 9, 'Click "Immerse in Water" so M1 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water.', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M1 recorded - its row has been added to your Results Table.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0),
(@density_id, 10, 'Remove M1 from the thread (drag it away), then hang M2 on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M2 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 11, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M2''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M2 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 12, 'Click "Immerse in Water" so M2 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water.', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M2 recorded - its row has been added to your Results Table.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0),
(@density_id, 13, 'Remove M2 from the thread (drag it away), then hang M3 on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M3 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 14, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M3''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M3 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 15, 'Click "Immerse in Water" so M3 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water.', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M3 recorded - its row has been added to your Results Table.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0),
(@density_id, 16, 'Remove M3 from the thread (drag it away), then hang M4 on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M4 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 17, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M4''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M4 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 18, 'Click "Immerse in Water" so M4 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water.', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M4 recorded - its row has been added to your Results Table.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0),
(@density_id, 19, 'Remove M4 from the thread (drag it away), then hang M5 on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M5 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 20, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M5''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M5 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 21, 'Click "Immerse in Water" so M5 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water.', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M5 recorded - its row has been added to your Results Table.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0),
(@density_id, 22, 'Remove M5 from the thread (drag it away), then hang M6 on the spring''s thread - drag it to just above the beaker.', NULL, 'move', 'spring1', NULL, 'Drop the sample just above the beaker, under the spring.', 'M6 is hanging freely in air.', 'Drag the sample to the end of the thread, just above the beaker.', 0),
(@density_id, 23, 'Wait for the pointer to stop moving, then select the rule, click Measure and click the spring to record M6''s reading in air.', NULL, 'measure', NULL, NULL, 'Take the reading only once the pointer is stationary.', 'Air reading for M6 recorded.', 'Select the rule, click Measure, then click the spring.', 0),
(@density_id, 24, 'Click "Immerse in Water" so M6 is completely under water without touching the beaker, wait for the pointer to settle, then measure the reading in water. Your Results Table is now complete - which samples are consistent with pure silver?', NULL, 'measure', NULL, NULL, 'The pointer moves up when the sample is immersed - the water''s upthrust takes some of its weight.', 'M6 recorded - its row has been added to your Results Table. All six samples are done.', 'Immerse the sample, then select the rule, click Measure and click the spring.', 0);

INSERT INTO `virtual_lab_graph_configs` (`experiment_id`, `enabled`, `title`, `x_column`, `y_column`, `x_label`, `y_label`, `graph_type`, `allow_axis_change`, `min_points`, `show_best_fit`, `manual_plot`)
VALUES (@density_id, 1, 'Density of each metal sample', 'metal_number', 'density_kgm3', 'Metal sample number', 'Density (kg/m3)', 'scatter', 0, 6, 0, 0);

INSERT INTO `virtual_lab_questions` (`experiment_id`, `question_number`, `question_text`, `question_type`, `stage`, `requirement`, `linked_to_graph`, `marks`) VALUES
(@density_id, 1, 'For each metal sample, show your calculation of e_a = air reading - reference, e_w = water reading - reference, relative density R.D. = e_a / (e_a - e_w), and density = 1000 x R.D. (kg/m3). Check these match the values your Results Table filled in automatically.', 'calculation', 'after_experiment', 'notebook_only', 0, 6.00),
(@density_id, 2, 'Pure silver has a density of 10200 to 10500 kg/m3. Using your graph, state which of the six metal samples (M1-M6), if any, are consistent with pure silver, and advise your friends accordingly.', 'short_answer', 'after_experiment', 'notebook_only', 1, 6.00),
(@density_id, 3, 'All six samples have the same mass (100g) and gave roughly the same reading in air, yet their readings in water were different. Explain why.', 'short_answer', 'after_experiment', 'notebook_only', 0, 5.00),
(@density_id, 4, 'State one precaution you took when immersing a sample in the water, and explain why it matters.', 'short_answer', 'after_experiment', 'notebook_only', 0, 3.00);
