-- New admin-curated template: "Experimental Determination of Acceleration Due to Gravity"
-- (Physics Practical Workbook: the grandfather, the falling mangoes and "bodies fall at about 10 m/s²").
-- A separate experiment from the existing "Simple Pendulum" (template 12 and its copies are untouched).
--
-- Reuses the pendulum lab (VirtualLabScenePendulum.vue) with render_component 'pendulum_gravity' and the
-- bob prop experiment = 'determine_g', which switches that scene to this practical's configuration:
-- Earth's real g (9.81), the same 50 g bob throughout, lengths 0.100-0.600 m on a 65 cm rule, length
-- measured to the centre of the bob (thread / top-of-bob clicks are refused with a warning), small-angle
-- release check (> 10 degrees warns; the release step accepts up to 10), a 0.01 s stopwatch with a live
-- "n / 20" oscillation counter, reset-before-timing and let-it-settle checks, a read-out refused unless
-- exactly 20 oscillations were timed, and a stand that, if knocked, makes the swing elliptical until
-- steadied. The swing is a real damped simulation, so t comes from the student's own timing.
--
-- The student types t for each length into the results table (VirtualLabGravityAnalysis.vue): T = t/20
-- and T^2 are worked out with the working shown; they plot T^2 against l themselves
-- (VirtualLabStudentGraph.vue), find S = dT^2/dl and g = 4 pi^2 / S, say whether it supports 10 m/s^2,
-- write a conclusion, choose errors/precautions and get a 17-criterion assessment. Each stopwatch
-- reading is also kept as a 'Timing l = ... m' calculation entry, to check the typed times against.
-- Safe to re-run.

INSERT INTO `virtual_lab_experiments`
    (`title`, `subject_id`, `topic`, `category`, `difficulty`, `created_by`, `objective`, `introduction`, `apparatus`, `materials`, `safety_precautions`, `scene_objects`, `conclusion_prompt`, `marks`, `is_template`, `status`, `render_mode`, `render_component`, `template_key`, `template_version`)
SELECT
    'Experimental Determination of Acceleration Due to Gravity', (SELECT id FROM subjects WHERE name = 'PHY' LIMIT 1), 'Mechanics: Acceleration due to gravity', 'physics', 'intermediate', NULL,
    'To determine the value of acceleration due to gravity, g, using a simple pendulum.',
    'An old man and his grandson, who had grown up with his parents in the city, were very hungry after working in a garden. While resting under a mango tree, a ripe mango fell from the tree.\nThe grandson became excited because he wanted to get more ripe mangoes to eat before proceeding home for lunch. His grandfather advised him that if he could climb up the tree and shake the branches, the ripe mangoes would fall to the ground. The grandson did exactly that and many ripe mangoes fell to the ground.\nWhile eating with his grandfather, the grandson told him that their Physics teacher had explained that mangoes fall from trees because of the force of gravity acting on them, and that bodies fall freely at approximately 10 m/s².\nThe old man wanted to know how the teacher arrived at this value, and challenged his grandson to prove experimentally that bodies fall freely at approximately 10 m/s². The grandson therefore decides to use a pendulum experiment to determine the acceleration due to gravity.',
    'One piece of thread (about 110.0 cm), one pendulum bob, one metre rule, one retort stand with clamp, one stopwatch/stop clock, two small pieces of wood.',
    'None (all apparatus is simulated).',
    'Keep the angle of swing small; make sure the retort stand is stable and the bob swings in one vertical plane; avoid draughts from doors, windows and fans.',
    '[{"key":"bob1","object_type":"specimen","position":{"x":-0.8,"y":0,"z":0},"props":{"length_cm":30,"mass_g":50,"experiment":"determine_g"}},{"key":"ruler1","object_type":"ruler","position":{"x":0.8,"y":0,"z":0.8}},{"key":"stopwatch1","object_type":"stopwatch","position":{"x":0.8,"y":0,"z":-0.8}}]',
    'Does your experimental value of g support the statement that bodies fall freely at approximately 10 m/s²?',
    40.00, 1, 'published', '2d', 'pendulum_gravity', 'physics_gravity_pendulum', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `virtual_lab_experiments` WHERE `template_key` = 'physics_gravity_pendulum');

SET @g_id = (SELECT id FROM `virtual_lab_experiments` WHERE `template_key` = 'physics_gravity_pendulum' LIMIT 1);

DELETE FROM `virtual_lab_steps` WHERE `experiment_id` = @g_id;
INSERT INTO `virtual_lab_steps` (`experiment_id`, `step_number`, `instruction`, `target_object_key`, `required_action`, `expected_value`, `tolerance`, `hint`, `feedback_correct`, `feedback_incorrect`, `is_safety_check`) VALUES
(@g_id, 1, 'Check the set-up: the pendulum bob should hang freely on its thread from the clamp. Select the bob and click Inspect.', 'bob1', 'inspect', NULL, NULL, 'Click the brass bob, then Inspect.', 'The bob hangs freely from the clamp.', 'Select the bob and click Inspect.', 0),
(@g_id, 2, 'Check that the metre rule is positioned beside the pendulum. Select the rule and click Inspect.', 'ruler1', 'inspect', NULL, NULL, 'Click the yellow rule hanging beside the pendulum, then Inspect.', 'The metre rule is beside the pendulum, reading down from the point of suspension.', 'Select the metre rule and click Inspect.', 0),
(@g_id, 3, 'Adjust the length of the pendulum to l = 0.100 m with the length control.', 'bob1', 'move', '0.100', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.100 m.', 'Set the length to exactly 0.100 m.', 0),
(@g_id, 4, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 5, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 6, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 7, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 8, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.100 m row of the results table below the lab.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.100 m.', 'Click Read Time, then Record.', 0),
(@g_id, 9, 'Reset the stopwatch, then change the length of the pendulum to l = 0.200 m.', 'bob1', 'move', '0.200', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.200 m.', 'Set the length to exactly 0.200 m.', 0),
(@g_id, 10, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 11, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 12, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 13, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 14, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.200 m row of the results table below the lab.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.200 m.', 'Click Read Time, then Record.', 0),
(@g_id, 15, 'Reset the stopwatch, then change the length of the pendulum to l = 0.300 m.', 'bob1', 'move', '0.300', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.300 m.', 'Set the length to exactly 0.300 m.', 0),
(@g_id, 16, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 17, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 18, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 19, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 20, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.300 m row of the results table below the lab.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.300 m.', 'Click Read Time, then Record.', 0),
(@g_id, 21, 'Reset the stopwatch, then change the length of the pendulum to l = 0.400 m.', 'bob1', 'move', '0.400', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.400 m.', 'Set the length to exactly 0.400 m.', 0),
(@g_id, 22, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 23, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 24, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 25, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 26, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.400 m row of the results table below the lab.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.400 m.', 'Click Read Time, then Record.', 0),
(@g_id, 27, 'Reset the stopwatch, then change the length of the pendulum to l = 0.500 m.', 'bob1', 'move', '0.500', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.500 m.', 'Set the length to exactly 0.500 m.', 0),
(@g_id, 28, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 29, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 30, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 31, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 32, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.500 m row of the results table below the lab.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.500 m.', 'Click Read Time, then Record.', 0),
(@g_id, 33, 'Reset the stopwatch, then change the length of the pendulum to l = 0.600 m.', 'bob1', 'move', '0.600', 0.0005, 'Use the Length l slider at the bottom of the lab.', 'l = 0.600 m.', 'Set the length to exactly 0.600 m.', 0),
(@g_id, 34, 'Measure l with the metre rule, from the point of suspension to the centre of the bob: select the rule, click Measure, click the centre of the bob, then Record.', 'ruler1', 'measure', NULL, NULL, 'Click the middle of the bob - not the thread, not the top of the bob.', 'Length measured to the centre of the bob.', 'Select the rule, click Measure, then click the centre of the bob.', 0),
(@g_id, 35, 'Displace the bob sideways through a small angle (less than 10°) and release it gently, without pushing it.', 'bob1', 'rotate', '5', 5, 'Drag the bob a little to one side - watch the angle - and let go.', 'Released from a small angle.', 'Use a small angular displacement (less than 10°) for accurate results.', 0),
(@g_id, 36, 'Let the first few oscillations pass so the swing is regular, then start the stopwatch as the bob passes the centre.', 'stopwatch1', 'switch_on', NULL, NULL, 'Wait until the oscillations are steady, then click Start.', 'Timing started.', 'Start the stopwatch now.', 0),
(@g_id, 37, 'Count 20 complete oscillations (watch the counter) and stop the stopwatch immediately after the 20th.', 'stopwatch1', 'switch_off', NULL, NULL, 'Click Stop as the counter reaches 20 / 20.', 'Stopwatch stopped after 20 oscillations.', 'Stop the stopwatch after the 20th oscillation.', 0),
(@g_id, 38, 'Click Read Time and Record the time t for 20 oscillations, then type it into the l = 0.600 m row of the results table below the lab. That is all six lengths - now plot T² against l below.', 'stopwatch1', 'measure', NULL, NULL, 'Read Time, then Record. Type the same time into the table.', 't recorded for l = 0.600 m.', 'Click Read Time, then Record.', 0);

INSERT INTO `virtual_lab_graph_configs` (`experiment_id`, `enabled`, `title`, `x_column`, `y_column`, `x_label`, `y_label`, `graph_type`, `allow_axis_change`, `min_points`, `show_best_fit`, `manual_plot`)
VALUES (@g_id, 1, 'T squared against l', 'length_m', 'period_squared_s2', 'Length, l (m)', 'Period squared, T^2 (s^2)', 'scatter', 0, 6, 1, 0)
ON DUPLICATE KEY UPDATE `enabled` = VALUES(`enabled`), `title` = VALUES(`title`), `x_column` = VALUES(`x_column`), `y_column` = VALUES(`y_column`),
    `x_label` = VALUES(`x_label`), `y_label` = VALUES(`y_label`), `graph_type` = VALUES(`graph_type`), `allow_axis_change` = VALUES(`allow_axis_change`),
    `min_points` = VALUES(`min_points`), `show_best_fit` = VALUES(`show_best_fit`), `manual_plot` = VALUES(`manual_plot`);
